package com.foxconn.cnsbg.escort.subsys.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.foxconn.cnsbg.escort.subsys.dao.CachedBleData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CACHED_BLE_DATA.
*/
public class CachedBleDataDao extends AbstractDao<CachedBleData, Long> {

    public static final String TABLENAME = "CACHED_BLE_DATA";

    /**
     * Properties of entity CachedBleData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceID = new Property(1, String.class, "deviceID", false, "DEVICE_ID");
        public final static Property CarID = new Property(2, String.class, "carID", false, "CAR_ID");
        public final static Property Time = new Property(3, java.util.Date.class, "time", false, "TIME");
        public final static Property Mac = new Property(4, String.class, "mac", false, "MAC");
        public final static Property Rssi = new Property(5, Integer.class, "rssi", false, "RSSI");
        public final static Property BatteryLevel = new Property(6, Integer.class, "batteryLevel", false, "BATTERY_LEVEL");
        public final static Property SignalStrength = new Property(7, Integer.class, "signalStrength", false, "SIGNAL_STRENGTH");
        public final static Property LockStatus = new Property(8, String.class, "lockStatus", false, "LOCK_STATUS");
        public final static Property DoorStatus = new Property(9, String.class, "doorStatus", false, "DOOR_STATUS");
    };


    public CachedBleDataDao(DaoConfig config) {
        super(config);
    }
    
    public CachedBleDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CACHED_BLE_DATA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DEVICE_ID' TEXT," + // 1: deviceID
                "'CAR_ID' TEXT," + // 2: carID
                "'TIME' INTEGER," + // 3: time
                "'MAC' TEXT," + // 4: mac
                "'RSSI' INTEGER," + // 5: rssi
                "'BATTERY_LEVEL' INTEGER," + // 6: batteryLevel
                "'SIGNAL_STRENGTH' INTEGER," + // 7: signalStrength
                "'LOCK_STATUS' TEXT," + // 8: lockStatus
                "'DOOR_STATUS' TEXT);"); // 9: doorStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CACHED_BLE_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CachedBleData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceID = entity.getDeviceID();
        if (deviceID != null) {
            stmt.bindString(2, deviceID);
        }
 
        String carID = entity.getCarID();
        if (carID != null) {
            stmt.bindString(3, carID);
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time.getTime());
        }
 
        String mac = entity.getMac();
        if (mac != null) {
            stmt.bindString(5, mac);
        }
 
        Integer rssi = entity.getRssi();
        if (rssi != null) {
            stmt.bindLong(6, rssi);
        }
 
        Integer batteryLevel = entity.getBatteryLevel();
        if (batteryLevel != null) {
            stmt.bindLong(7, batteryLevel);
        }
 
        Integer signalStrength = entity.getSignalStrength();
        if (signalStrength != null) {
            stmt.bindLong(8, signalStrength);
        }
 
        String lockStatus = entity.getLockStatus();
        if (lockStatus != null) {
            stmt.bindString(9, lockStatus);
        }
 
        String doorStatus = entity.getDoorStatus();
        if (doorStatus != null) {
            stmt.bindString(10, doorStatus);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CachedBleData readEntity(Cursor cursor, int offset) {
        CachedBleData entity = new CachedBleData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // deviceID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // carID
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // time
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mac
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // rssi
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // batteryLevel
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // signalStrength
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // lockStatus
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // doorStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CachedBleData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCarID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setMac(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRssi(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setBatteryLevel(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setSignalStrength(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setLockStatus(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDoorStatus(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CachedBleData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CachedBleData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
