package com.foxconn.cnsbg.escort.subsys.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHED_BLE_DATA.
 */
public class CachedBleData {

    private Long id;
    private String deviceID;
    private String carID;
    private java.util.Date time;
    private String mac;
    private Integer rssi;
    private Integer batteryLevel;
    private Integer signalStrength;
    private String lockStatus;
    private String doorStatus;

    public CachedBleData() {
    }

    public CachedBleData(Long id) {
        this.id = id;
    }

    public CachedBleData(Long id, String deviceID, String carID, java.util.Date time, String mac, Integer rssi, Integer batteryLevel, Integer signalStrength, String lockStatus, String doorStatus) {
        this.id = id;
        this.deviceID = deviceID;
        this.carID = carID;
        this.time = time;
        this.mac = mac;
        this.rssi = rssi;
        this.batteryLevel = batteryLevel;
        this.signalStrength = signalStrength;
        this.lockStatus = lockStatus;
        this.doorStatus = doorStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceID() {
        return deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    public String getCarID() {
        return carID;
    }

    public void setCarID(String carID) {
        this.carID = carID;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getMac() {
        return mac;
    }

    public void setMac(String mac) {
        this.mac = mac;
    }

    public Integer getRssi() {
        return rssi;
    }

    public void setRssi(Integer rssi) {
        this.rssi = rssi;
    }

    public Integer getBatteryLevel() {
        return batteryLevel;
    }

    public void setBatteryLevel(Integer batteryLevel) {
        this.batteryLevel = batteryLevel;
    }

    public Integer getSignalStrength() {
        return signalStrength;
    }

    public void setSignalStrength(Integer signalStrength) {
        this.signalStrength = signalStrength;
    }

    public String getLockStatus() {
        return lockStatus;
    }

    public void setLockStatus(String lockStatus) {
        this.lockStatus = lockStatus;
    }

    public String getDoorStatus() {
        return doorStatus;
    }

    public void setDoorStatus(String doorStatus) {
        this.doorStatus = doorStatus;
    }

}
