package com.foxconn.cnsbg.escort.subsys.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHED_LOC_DATA.
 */
public class CachedLocData {

    private Long id;
    private String deviceID;
    private String carID;
    private java.util.Date time;
    private Double latitude;
    private Double longitude;
    private String provider;
    private Float accuracy;
    private Double altitude;
    private Float bearing;
    private Float speed;
    private Boolean mock;
    private Integer batteryLevel;
    private Integer signalStrength;
    private String lockStatus;
    private String doorStatus;

    public CachedLocData() {
    }

    public CachedLocData(Long id) {
        this.id = id;
    }

    public CachedLocData(Long id, String deviceID, String carID, java.util.Date time, Double latitude, Double longitude, String provider, Float accuracy, Double altitude, Float bearing, Float speed, Boolean mock, Integer batteryLevel, Integer signalStrength, String lockStatus, String doorStatus) {
        this.id = id;
        this.deviceID = deviceID;
        this.carID = carID;
        this.time = time;
        this.latitude = latitude;
        this.longitude = longitude;
        this.provider = provider;
        this.accuracy = accuracy;
        this.altitude = altitude;
        this.bearing = bearing;
        this.speed = speed;
        this.mock = mock;
        this.batteryLevel = batteryLevel;
        this.signalStrength = signalStrength;
        this.lockStatus = lockStatus;
        this.doorStatus = doorStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceID() {
        return deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    public String getCarID() {
        return carID;
    }

    public void setCarID(String carID) {
        this.carID = carID;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public Float getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Float accuracy) {
        this.accuracy = accuracy;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    public Float getBearing() {
        return bearing;
    }

    public void setBearing(Float bearing) {
        this.bearing = bearing;
    }

    public Float getSpeed() {
        return speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Boolean getMock() {
        return mock;
    }

    public void setMock(Boolean mock) {
        this.mock = mock;
    }

    public Integer getBatteryLevel() {
        return batteryLevel;
    }

    public void setBatteryLevel(Integer batteryLevel) {
        this.batteryLevel = batteryLevel;
    }

    public Integer getSignalStrength() {
        return signalStrength;
    }

    public void setSignalStrength(Integer signalStrength) {
        this.signalStrength = signalStrength;
    }

    public String getLockStatus() {
        return lockStatus;
    }

    public void setLockStatus(String lockStatus) {
        this.lockStatus = lockStatus;
    }

    public String getDoorStatus() {
        return doorStatus;
    }

    public void setDoorStatus(String doorStatus) {
        this.doorStatus = doorStatus;
    }

}
