package com.foxconn.cnsbg.escort.subsys.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHED_LOCATION_ENTITY.
 */
public class CachedLocationEntity {

    private Long id;
    private String UDID;
    private Long datetimestamp;
    private Integer latitudeE6;
    private Integer longitudeE6;

    public CachedLocationEntity() {
    }

    public CachedLocationEntity(Long id) {
        this.id = id;
    }

    public CachedLocationEntity(Long id, String UDID, Long datetimestamp, Integer latitudeE6, Integer longitudeE6) {
        this.id = id;
        this.UDID = UDID;
        this.datetimestamp = datetimestamp;
        this.latitudeE6 = latitudeE6;
        this.longitudeE6 = longitudeE6;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUDID() {
        return UDID;
    }

    public void setUDID(String UDID) {
        this.UDID = UDID;
    }

    public Long getDatetimestamp() {
        return datetimestamp;
    }

    public void setDatetimestamp(Long datetimestamp) {
        this.datetimestamp = datetimestamp;
    }

    public Integer getLatitudeE6() {
        return latitudeE6;
    }

    public void setLatitudeE6(Integer latitudeE6) {
        this.latitudeE6 = latitudeE6;
    }

    public Integer getLongitudeE6() {
        return longitudeE6;
    }

    public void setLongitudeE6(Integer longitudeE6) {
        this.longitudeE6 = longitudeE6;
    }

}
