package com.foxconn.cnsbg.escort.subsys.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHED_ACCELERATION_ENTITY.
 */
public class CachedAccelerationEntity {

    private Long id;
    private String UDID;
    private Long datetimestamp;
    private Float accelX_avg;
    private Float accelY_avg;
    private Float accelZ_avg;
    private Double accelX_stddev;
    private Double accelY_stddev;
    private Double accelZ_stddev;

    public CachedAccelerationEntity() {
    }

    public CachedAccelerationEntity(Long id) {
        this.id = id;
    }

    public CachedAccelerationEntity(Long id, String UDID, Long datetimestamp, Float accelX_avg, Float accelY_avg, Float accelZ_avg, Double accelX_stddev, Double accelY_stddev, Double accelZ_stddev) {
        this.id = id;
        this.UDID = UDID;
        this.datetimestamp = datetimestamp;
        this.accelX_avg = accelX_avg;
        this.accelY_avg = accelY_avg;
        this.accelZ_avg = accelZ_avg;
        this.accelX_stddev = accelX_stddev;
        this.accelY_stddev = accelY_stddev;
        this.accelZ_stddev = accelZ_stddev;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUDID() {
        return UDID;
    }

    public void setUDID(String UDID) {
        this.UDID = UDID;
    }

    public Long getDatetimestamp() {
        return datetimestamp;
    }

    public void setDatetimestamp(Long datetimestamp) {
        this.datetimestamp = datetimestamp;
    }

    public Float getAccelX_avg() {
        return accelX_avg;
    }

    public void setAccelX_avg(Float accelX_avg) {
        this.accelX_avg = accelX_avg;
    }

    public Float getAccelY_avg() {
        return accelY_avg;
    }

    public void setAccelY_avg(Float accelY_avg) {
        this.accelY_avg = accelY_avg;
    }

    public Float getAccelZ_avg() {
        return accelZ_avg;
    }

    public void setAccelZ_avg(Float accelZ_avg) {
        this.accelZ_avg = accelZ_avg;
    }

    public Double getAccelX_stddev() {
        return accelX_stddev;
    }

    public void setAccelX_stddev(Double accelX_stddev) {
        this.accelX_stddev = accelX_stddev;
    }

    public Double getAccelY_stddev() {
        return accelY_stddev;
    }

    public void setAccelY_stddev(Double accelY_stddev) {
        this.accelY_stddev = accelY_stddev;
    }

    public Double getAccelZ_stddev() {
        return accelZ_stddev;
    }

    public void setAccelZ_stddev(Double accelZ_stddev) {
        this.accelZ_stddev = accelZ_stddev;
    }

}
