package com.foxconn.cnsbg.escort.subsys.dao;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MAIN_USER_ENTITY.
 */
public class MainUserEntity {

    private Long id;
    private String mainusername;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MainUserEntityDao myDao;

    private List<UserEntity> friends;
    private List<UserEntity> invites;

    public MainUserEntity() {
    }

    public MainUserEntity(Long id) {
        this.id = id;
    }

    public MainUserEntity(Long id, String mainusername) {
        this.id = id;
        this.mainusername = mainusername;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMainUserEntityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMainusername() {
        return mainusername;
    }

    public void setMainusername(String mainusername) {
        this.mainusername = mainusername;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<UserEntity> getFriends() {
        if (friends == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserEntityDao targetDao = daoSession.getUserEntityDao();
            List<UserEntity> friendsNew = targetDao._queryMainUserEntity_Friends(id);
            synchronized (this) {
                if(friends == null) {
                    friends = friendsNew;
                }
            }
        }
        return friends;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetFriends() {
        friends = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<UserEntity> getInvites() {
        if (invites == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserEntityDao targetDao = daoSession.getUserEntityDao();
            List<UserEntity> invitesNew = targetDao._queryMainUserEntity_Invites(id);
            synchronized (this) {
                if(invites == null) {
                    invites = invitesNew;
                }
            }
        }
        return invites;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetInvites() {
        invites = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
